name: assessment
description: A new Flutter project.

publish_to: 'none'

version: 1.10.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Presentation
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  go_router: ^14.1.4

  # Data
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Other
  logger: ^2.3.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true
  assets:
    - assets/animation/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
