name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm ci
      - name: Run semantic-release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update pubspec.yaml
        if: steps.semantic_release.outputs.nextRelease.version != ''
        run: |
          version=$(npx -c 'echo "$npm_package_version"')
          echo "Updating pubspec.yaml with version $version"
          sed -i "s/version: .*/version: $version/" pubspec.yaml
          echo "Updated pubspec.yaml content:"
          cat pubspec.yaml
      - name: Commit updated pubspec.yaml
        if: steps.semantic_release.outputs.nextRelease.version != ''
        run: |
          echo "Committing updated pubspec.yaml"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          git commit -m "chore: update pubspec.yaml to version $version"
          git push origin main
          echo "Committed and pushed updated pubspec.yaml"
