name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update pubspec.yaml
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          version=$(node -p "require('./package.json').version")
          sed -i '' "s/version: .*/version: $version/" pubspec.yaml

      - name: Commit updated pubspec.yaml
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          git commit -m "chore: update pubspec.yaml to version $version"
          git push origin main